    <script>document.addEventListener('error',function(e){var t=e.target;if(t.tagName==='IMG'&&t.src.indexOf('/imgp/')!==-1){t.src=t.src.replace('/imgp/','/imgr/');t.srcset=t.srcset?t.srcset.replace(/\/imgp\//g,'/imgr/'):''}},true)</script>
    <script>document.addEventListener('click',function(e){document.querySelectorAll('details.js-click-away[open]').forEach(function(d){if(!d.contains(e.target))d.removeAttribute('open')})})</script>
    <script>document.addEventListener('click',function(e){var t=e.target.closest('[data-toggle-target]');if(!t)return;e.preventDefault();var sel=t.getAttribute('data-toggle-target');var target=sel&&document.querySelector(sel);if(!target)return;var open=!target.classList.contains('is-open');target.classList.toggle('is-open',open);t.setAttribute('aria-expanded',open?'true':'false')})</script>
    {{-- The chevron in a copied FAQ turned through the source site's own
         animation code, which was stripped with its scripts. !important beats
         the inline transform such exports leave on the arrow. --}}
    <style>[data-vela-disclosure] [class*="arrow"],[data-vela-disclosure] [class*="chevron"],[data-vela-disclosure] [class*="caret"]{transition:transform .2s ease}[data-vela-disclosure][aria-expanded="true"] [class*="arrow"],[data-vela-disclosure][aria-expanded="true"] [class*="chevron"],[data-vela-disclosure][aria-expanded="true"] [class*="caret"]{transform:rotate(180deg) !important}</style>
    {{-- A copied accordion arrives without its script; the pairs are marked at render time and this opens them. --}}
    <script>(function(){function t(g){var p=document.getElementById(g.getAttribute('data-vela-disclosure'));if(!p)return;var o=g.getAttribute('aria-expanded')!=='true';g.setAttribute('aria-expanded',o?'true':'false');g.setAttribute('data-state',o?'open':'closed');p.setAttribute('data-state',o?'open':'closed');p.style.display=o?'block':'none';if(o){p.style.maxHeight='none';p.style.height='auto';p.style.overflow='visible';p.style.visibility='visible';p.style.opacity='1'}}document.addEventListener('click',function(e){var g=e.target.closest('[data-vela-disclosure]');if(!g)return;if(e.target.closest('a[href],button:not([data-vela-disclosure]),input,select,textarea'))return;e.preventDefault();t(g)});document.addEventListener('keydown',function(e){if(e.key!=='Enter'&&e.key!==' ')return;var g=e.target.closest('[data-vela-disclosure]');if(!g||g.tagName==='BUTTON'||g.tagName==='A')return;e.preventDefault();t(g)})})()</script>
    <script>document.addEventListener('click',function(e){var b=e.target.closest('[data-code-copy]');if(!b)return;var c=b.closest('.block-code');if(!c)return;var code=c.querySelector('.block-code-body');if(!code||!navigator.clipboard)return;navigator.clipboard.writeText(code.textContent||'').then(function(){var l=b.querySelector('.block-code-copy-label')||b;var o=l.textContent;b.classList.add('is-copied');l.textContent='Copied';setTimeout(function(){b.classList.remove('is-copied');l.textContent=o},1500)})})</script>
@if(vela_config('pwa_enabled', '1') !== '0')
    @include('vela::partials.pwa-registration')
@endif
    @include('vela::partials.cookie-consent')
    @include('vela::partials.webmcp')
