    <script>document.addEventListener('error',function(e){var t=e.target;if(t.tagName==='IMG'&&t.src.indexOf('/imgp/')!==-1){t.src=t.src.replace('/imgp/','/imgr/');t.srcset=t.srcset?t.srcset.replace(/\/imgp\//g,'/imgr/'):''}},true)</script>
    <script>document.addEventListener('click',function(e){document.querySelectorAll('details.js-click-away[open]').forEach(function(d){if(!d.contains(e.target))d.removeAttribute('open')})})</script>
    <script>document.addEventListener('click',function(e){var t=e.target.closest('[data-toggle-target]');if(!t)return;e.preventDefault();var sel=t.getAttribute('data-toggle-target');var target=sel&&document.querySelector(sel);if(!target)return;var open=!target.classList.contains('is-open');target.classList.toggle('is-open',open);t.setAttribute('aria-expanded',open?'true':'false')})</script>
    {{-- A copied carousel loses the script that moved it; the track is marked
         at render time and driven here as a scroll-snapping strip, which
         swipes on a phone and scrolls on a trackpad without any of it. --}}
    <style>[data-vela-carousel-track]{display:flex!important;flex-wrap:nowrap!important;overflow-x:auto!important;white-space:normal!important;scroll-snap-type:x mandatory;scroll-behavior:smooth;-webkit-overflow-scrolling:touch;scrollbar-width:none}[data-vela-carousel-track]::-webkit-scrollbar{display:none}[data-vela-slide]{flex:0 0 auto!important;scroll-snap-align:start}[data-vela-carousel-prev],[data-vela-carousel-next]{cursor:pointer}[data-vela-carousel-dots]{display:flex;gap:8px;justify-content:center;align-items:center}[data-vela-carousel-dot]{width:8px;height:8px;padding:0;border:0;border-radius:999px;background:currentColor;opacity:.35;cursor:pointer;transition:opacity .2s ease}[data-vela-carousel-dot][aria-current="true"]{opacity:1}@media (prefers-reduced-motion:reduce){[data-vela-carousel-track]{scroll-behavior:auto}}</style>
    <script>(function(){function track(id){return document.querySelector('[data-vela-carousel-track="'+id+'"]')}function slides(t){return [].slice.call(t.querySelectorAll('[data-vela-slide]'))}function offset(t,el){return el.getBoundingClientRect().left-t.getBoundingClientRect().left+t.scrollLeft}function go(t,el){t.scrollTo({left:offset(t,el),behavior:'smooth'})}function step(t,dir){var s=slides(t),x=t.scrollLeft,target=null,i;if(dir>0){for(i=0;i<s.length;i++){if(offset(t,s[i])>x+2){target=s[i];break}}}else{for(i=s.length-1;i>=0;i--){if(offset(t,s[i])<x-2){target=s[i];break}}}
/* Past the end, come back round: an arrow that stops responding reads as broken. */
if(!target)target=dir>0?s[0]:s[s.length-1];if(target)go(t,target)}function mark(t){var d=document.querySelector('[data-vela-carousel-dots="'+t.getAttribute('data-vela-carousel-track')+'"]');if(!d)return;var s=slides(t),best=Infinity,at=0;s.forEach(function(el,k){var v=Math.abs(offset(t,el)-t.scrollLeft);if(v<best){best=v;at=k}});[].forEach.call(d.querySelectorAll('[data-vela-carousel-dot]'),function(b,k){b.setAttribute('aria-current',k===at?'true':'false')})}function hit(e){var p=e.target.closest('[data-vela-carousel-prev]');if(p){var t=track(p.getAttribute('data-vela-carousel-prev'));if(t){e.preventDefault();step(t,-1)}return true}var n=e.target.closest('[data-vela-carousel-next]');if(n){var t2=track(n.getAttribute('data-vela-carousel-next'));if(t2){e.preventDefault();step(t2,1)}return true}var d=e.target.closest('[data-vela-carousel-dot]');if(d){var w=d.closest('[data-vela-carousel-dots]');var t3=w&&track(w.getAttribute('data-vela-carousel-dots'));if(t3){e.preventDefault();var s=slides(t3)[parseInt(d.getAttribute('data-vela-carousel-dot'),10)];if(s)go(t3,s)}return true}return false}document.addEventListener('click',hit);document.addEventListener('keydown',function(e){if(e.key!=='Enter'&&e.key!==' ')return;if(e.target.closest('[data-vela-carousel-prev],[data-vela-carousel-next],[data-vela-carousel-dot]'))hit(e)});document.addEventListener('scroll',function(e){var t=e.target;if(t&&t.getAttribute&&t.getAttribute('data-vela-carousel-track'))mark(t)},true);document.addEventListener('DOMContentLoaded',function(){[].forEach.call(document.querySelectorAll('[data-vela-carousel-track]'),mark)})})()</script>
    {{-- The chevron in a copied FAQ turned through the source site's own
         animation code, which was stripped with its scripts. !important beats
         the inline transform such exports leave on the arrow. --}}
    <style>[data-vela-disclosure] [class*="arrow"],[data-vela-disclosure] [class*="chevron"],[data-vela-disclosure] [class*="caret"]{transition:transform .2s ease}[data-vela-disclosure][aria-expanded="true"] [class*="arrow"],[data-vela-disclosure][aria-expanded="true"] [class*="chevron"],[data-vela-disclosure][aria-expanded="true"] [class*="caret"]{transform:rotate(180deg) !important}</style>
    {{-- A copied accordion arrives without its script; the pairs are marked at render time and this opens them. --}}
    <script>(function(){function t(g){var p=document.getElementById(g.getAttribute('data-vela-disclosure'));if(!p)return;var o=g.getAttribute('aria-expanded')!=='true';g.setAttribute('aria-expanded',o?'true':'false');g.setAttribute('data-state',o?'open':'closed');p.setAttribute('data-state',o?'open':'closed');p.style.display=o?'block':'none';if(o){p.style.maxHeight='none';p.style.height='auto';p.style.overflow='visible';p.style.visibility='visible';p.style.opacity='1'}}document.addEventListener('click',function(e){var g=e.target.closest('[data-vela-disclosure]');if(!g)return;if(e.target.closest('a[href],button:not([data-vela-disclosure]),input,select,textarea'))return;e.preventDefault();t(g)});document.addEventListener('keydown',function(e){if(e.key!=='Enter'&&e.key!==' ')return;var g=e.target.closest('[data-vela-disclosure]');if(!g||g.tagName==='BUTTON'||g.tagName==='A')return;e.preventDefault();t(g)})})()</script>
    <script>document.addEventListener('click',function(e){var b=e.target.closest('[data-code-copy]');if(!b)return;var c=b.closest('.block-code');if(!c)return;var code=c.querySelector('.block-code-body');if(!code||!navigator.clipboard)return;navigator.clipboard.writeText(code.textContent||'').then(function(){var l=b.querySelector('.block-code-copy-label')||b;var o=l.textContent;b.classList.add('is-copied');l.textContent='Copied';setTimeout(function(){b.classList.remove('is-copied');l.textContent=o},1500)})})</script>
@if(vela_config('pwa_enabled', '1') !== '0')
    @include('vela::partials.pwa-registration')
@endif
    @include('vela::partials.cookie-consent')
    @include('vela::partials.webmcp')
